version: '3'
services: 
  client: 
    container_name: client 
    image: client 
    ports: 
      - "3000:3000" 
    build: 
      context: ./client  
  server: 
    container_name: server 
    image: server 
    ports: 
      - "3002:3002" 
    build: 
      context: ./server 
  
  db: 
    platform: linux/x86_64 
    image: mysql:8.0  
    restart: always 
    environment: 
      - MYSQL_DATABASE=questionsDatabase    
      - MYSQL_ROOT_PASSWORD=  
    ports: 
      - "3306:3306" 
    expose: 
      - "3306" 
    volumes: 
      - my-db:/var/lib/mysql 

volumes:
  my-db: 